spring:
  application:
    name: app1
  datasource:
    url: jdbc:mysql://localhost:3306/crud_demo
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com:
      example: DEBUG
err:
  required: is required.
